name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:
    name: Test QEMU Exit
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        target: [aarch64-unknown-none-softfloat, riscv64gc-unknown-none-elf]

    steps:
      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: ${{ matrix.target }}
          components: llvm-tools-preview

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install QEMU
        run: |
          sudo apt update
          sudo apt install qemu-system

      - name: Run tests AARCH64
        if: matrix.target == 'aarch64-unknown-none-softfloat'
        run: |
          RUSTFLAGS="-C link-arg=-Ttests/aarch64_raspi3/link.ld" cargo test --target ${{ matrix.target }} --release

      - name: Run tests RISCV64
        if: matrix.target == 'riscv64gc-unknown-none-elf'
        run: |
          RUSTFLAGS="-C link-arg=-Ttests/riscv64_virt/link.ld" cargo test --target ${{ matrix.target }} --release
